### ISSUE TITLE
The type ManagedBean is deprecated

### ISSUE THREAD

**Issue by weichm** [PacktPublishing/Java-EE-8-Development-with-Eclipse-Third-Edition#1]
Eclipse is given me this warning (in the SECOND chapter, in https://github.com/PacktPublishing/Java-EE-8-Development-with-Eclipse-Third-Edition/blob/master/Chapter02/LoginJSFApp/src/packt/book/jee_eclipse/bean/LoginBean.java)

```
package packt.book.jee_eclipse.bean;
import javax.faces.bean.ManagedBean;

@ManagedBean(="loginBean")
public class LoginBean {

}
```

Strange, as the book seems the treat newer stuff: "Java EE 8 Development" in the title and the like...

Also see this answer, dating  back to 2016: https://stackoverflow.com/questions/38040947/the-type-managedbean-is-deprecated

**Comment by gaurav-packt** [comment]
If the issue still persists kindly reopen the issue.
