### ISSUE TITLE
Page 126 Datatype not supported

### ISSUE THREAD

**Issue by ghost** [PacktPublishing/Java-EE-8-Development-with-Eclipse-Third-Edition#2]
On page 126 of the book, in the Student table, enrolled_since has datatype LONG. 
LONG is however not a SQL datatype, or in fact a datatype in any RDBMS. 
What should this be?

[edit: it's on page 131 in the script. ought to be mediumtext]

Also, there are quite some other small mistakes so far. Such as using double quotes in a double quoted string (which is not possible without escaping them), or the code in the final section which is not the same as the code beforehand.

**Comment by packt-pradeeps** [comment]
Please elaborate and mention detailed description of these errors.
